version: '3.0'
services:
  server:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - default.env

  db:
    image: postgres:alpine
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db-data:/data/postgres
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
      PGDATA: /data/postgres

  # optional
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - '3001:3001'
    environment:
      PGADMIN_DEFAULT_EMAIL: changeme@changeme.com
      PGADMIN_DEFAULT_PASSWORD: changeme
      PGADMIN_LISTEN_PORT: 3001
    restart: unless-stopped

volumes:
  db-data:
